name: Python Pull Request workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run python manage.py test
        
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-